/*
 * File: app/store/MyStore.js
 *
 * This file was generated by Sencha Architect version 3.1.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.2.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.2.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('areaChart.store.MyStore', {
    extend: 'Ext.data.Store',

    requires: [
        'Ext.data.Field'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            storeId: 'MyStore',
            data: [
                {
                    name: 'January',
                    data1: 27,
                    data2: 65,
                    data3: 79,
                    data4: 99,
                    data5: 20,
                    data6: 52,
                    data7: 23,
                    data8: 20,
                    data9: 67
                },
                {
                    name: 'February',
                    data1: 28,
                    data2: 45,
                    data3: 21,
                    data4: 21,
                    data5: 99,
                    data6: 77,
                    data7: 80,
                    data8: 75,
                    data9: 92
                },
                {
                    name: 'March',
                    data1: 33,
                    data2: 20,
                    data3: 20,
                    data4: 20,
                    data5: 31,
                    data6: 96,
                    data7: 96,
                    data8: 31,
                    data9: 90
                },
                {
                    name: 'April',
                    data1: 97,
                    data2: 20,
                    data3: 46,
                    data4: 60,
                    data5: 20,
                    data6: 87,
                    data7: 88,
                    data8: 90,
                    data9: 89
                },
                {
                    name: 'May',
                    data1: 20,
                    data2: 42,
                    data3: 99,
                    data4: 79,
                    data5: 67,
                    data6: 26,
                    data7: 85,
                    data8: 72,
                    data9: 54
                },
                {
                    name: 'June',
                    data1: 20,
                    data2: 94,
                    data3: 79,
                    data4: 20,
                    data5: 28,
                    data6: 49,
                    data7: 20,
                    data8: 67,
                    data9: 60
                },
                {
                    name: 'July',
                    data1: 99,
                    data2: 66,
                    data3: 70,
                    data4: 32,
                    data5: 51,
                    data6: 30,
                    data7: 56,
                    data8: 96,
                    data9: 75
                },
                {
                    name: 'August',
                    data1: 42,
                    data2: 59,
                    data3: 23,
                    data4: 54,
                    data5: 29,
                    data6: 68,
                    data7: 20,
                    data8: 67,
                    data9: 48
                },
                {
                    name: 'September',
                    data1: 76,
                    data2: 20,
                    data3: 67,
                    data4: 53,
                    data5: 94,
                    data6: 39,
                    data7: 54,
                    data8: 88,
                    data9: 20
                },
                {
                    name: 'October',
                    data1: 58,
                    data2: 23,
                    data3: 23,
                    data4: 59,
                    data5: 63,
                    data6: 29,
                    data7: 20,
                    data8: 20,
                    data9: 25
                },
                {
                    name: 'November',
                    data1: 20,
                    data2: 73,
                    data3: 91,
                    data4: 53,
                    data5: 25,
                    data6: 64,
                    data7: 70,
                    data8: 20,
                    data9: 36
                },
                {
                    name: 'December',
                    data1: 20,
                    data2: 57,
                    data3: 20,
                    data4: 28,
                    data5: 50,
                    data6: 20,
                    data7: 59,
                    data8: 51,
                    data9: 47
                }
            ],
            fields: [
                {
                    name: 'name'
                },
                {
                    name: 'data1'
                },
                {
                    name: 'data2'
                },
                {
                    name: 'data3'
                },
                {
                    name: 'data4'
                },
                {
                    name: 'data5'
                },
                {
                    name: 'data6'
                },
                {
                    name: 'data7'
                }
            ]
        }, cfg)]);
    }
});