/*
 * File: app/view/TabbedForm.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.TabbedForm', {
    extend: 'Ext.form.Panel',
    alias: 'widget.tabbedform',

    border: 0,
    height: 187,
    width: 384,
    layout: {
        type: 'fit'
    },

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            items: [
                {
                    xtype: 'tabpanel',
                    activeTab: 0,
                    items: [
                        {
                            xtype: 'panel',
                            bodyPadding: 10,
                            title: 'Personal Details',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'First Name'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Last Name'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Company'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Email'
                                }
                            ]
                        },
                        {
                            xtype: 'panel',
                            bodyPadding: 10,
                            title: 'Phone Numbers',
                            items: [
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Home'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Business'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Mobile'
                                },
                                {
                                    xtype: 'textfield',
                                    fieldLabel: 'Fax'
                                }
                            ]
                        }
                    ]
                }
            ],
            dockedItems: [
                {
                    xtype: 'toolbar',
                    dock: 'bottom',
                    ui: 'footer',
                    items: [
                        {
                            xtype: 'tbfill'
                        },
                        {
                            xtype: 'button',
                            text: 'Save'
                        },
                        {
                            xtype: 'button',
                            text: 'Cancel'
                        }
                    ]
                }
            ]
        });

        me.callParent(arguments);
    }

});