/*
 * File: app/store/Plants.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('EditableGrid.store.Plants', {
    extend: 'Ext.data.Store',

    requires: [
        'EditableGrid.model.Plant'
    ],

    constructor: function(cfg) {
        var me = this;
        cfg = cfg || {};
        me.callParent([Ext.apply({
            autoLoad: true,
            storeId: 'MyArrayStore',
            model: 'EditableGrid.model.Plant',
            data: [
                {
                    common: 'Bloodroot',
                    botanical: 'Sanguinaria canadensis',
                    zone: '4',
                    light: 'Mostly Shady',
                    price: '2.44',
                    availability: '03/15/2006',
                    indoor: 'true'
                },
                {
                    common: 'Columbine',
                    botanical: 'Aquilegia canadensis',
                    zone: '3',
                    light: 'Mostly Shady',
                    price: '9.37',
                    availability: '03/06/2006',
                    indoor: 'true'
                },
                {
                    common: 'Marsh Marigold',
                    botanical: 'Caltha palustris',
                    zone: '4',
                    light: 'Mostly Sunny',
                    price: '6.81',
                    availability: '05/17/2006',
                    indoor: 'false'
                },
                {
                    common: 'Cowslip',
                    botanical: 'Caltha palustris',
                    zone: '4',
                    light: 'Mostly Shady',
                    price: '9.90',
                    availability: '03/06/2006',
                    indoor: 'true'
                },
                {
                    common: 'Dutchman\'s-Breeches',
                    botanical: 'Dicentra cucullaria',
                    zone: '3',
                    light: 'Mostly Shady',
                    price: '6.44',
                    availability: '01/20/2006',
                    indoor: 'true'
                },
                {
                    common: 'Ginger, Wild',
                    botanical: 'Asarum canadense',
                    zone: '3',
                    light: 'Mostly Shady',
                    price: '9.03',
                    availability: '04/18/2006',
                    indoor: 'true'
                },
                {
                    common: 'Hepatica',
                    botanical: 'Hepatica americana',
                    zone: '4',
                    light: 'Mostly Shady',
                    price: '4.45',
                    availability: '01/26/2006',
                    indoor: 'true'
                },
                {
                    common: 'Liverleaf',
                    botanical: 'Hepatica americana',
                    zone: '4',
                    light: 'Mostly Shady',
                    price: '3.99',
                    availability: '01/02/2006',
                    indoor: 'true'
                },
                {
                    common: 'Jack-In-The-Pulpit',
                    botanical: 'Arisaema triphyllum',
                    zone: '4',
                    light: 'Mostly Shady',
                    price: '3.23',
                    availability: '02/01/2006',
                    indoor: 'true'
                },
                {
                    common: 'Mayapple',
                    botanical: 'Podophyllum peltatum',
                    zone: '3',
                    light: 'Mostly Shady',
                    price: '2.98',
                    availability: '06/05/2006',
                    indoor: 'true'
                },
                {
                    common: 'Phlox, Woodland',
                    botanical: 'Phlox divaricata',
                    zone: '3',
                    light: 'Sun or Shade',
                    price: '2.80',
                    availability: '01/22/2006',
                    indoor: 'false'
                },
                {
                    common: 'Phlox, Blue',
                    botanical: 'Phlox divaricata',
                    zone: '3',
                    light: 'Sun or Shade',
                    price: '5.59',
                    availability: '02/16/2006',
                    indoor: 'false'
                },
                {
                    common: 'Spring-Beauty',
                    botanical: 'Claytonia Virginica',
                    zone: '7',
                    light: 'Mostly Shady',
                    price: '6.59',
                    availability: '02/01/2006',
                    indoor: 'true'
                },
                {
                    common: 'Trillium',
                    botanical: 'Trillium grandiflorum',
                    zone: '5',
                    light: 'Sun or Shade',
                    price: '3.90',
                    availability: '04/29/2006',
                    indoor: 'false'
                },
                {
                    common: 'Wake Robin',
                    botanical: 'Trillium grandiflorum',
                    zone: '5',
                    light: 'Sun or Shade',
                    price: '3.20',
                    availability: '02/21/2006',
                    indoor: 'false'
                },
                {
                    common: 'Violet, Dog-Tooth',
                    botanical: 'Erythronium americanum',
                    zone: '4',
                    light: 'Shade',
                    price: '9.04',
                    availability: '02/01/2006',
                    indoor: 'true'
                },
                {
                    common: 'Trout Lily',
                    botanical: 'Erythronium americanum',
                    zone: '4',
                    light: 'Shade',
                    price: '6.94',
                    availability: '03/24/2006',
                    indoor: 'true'
                },
                {
                    common: 'Adder\'s-Tongue',
                    botanical: 'Erythronium americanum',
                    zone: '4',
                    light: 'Shade',
                    price: '9.58',
                    availability: '04/13/2006',
                    indoor: 'true'
                },
                {
                    common: 'Anemone',
                    botanical: 'Anemone blanda',
                    zone: '6',
                    light: 'Mostly Shady',
                    price: '8.86',
                    availability: '12/26/2006',
                    indoor: 'true'
                },
                {
                    common: 'Grecian Windflower',
                    botanical: 'Anemone blanda',
                    zone: '6',
                    light: 'Mostly Shady',
                    price: '9.16',
                    availability: '07/10/2006',
                    indoor: 'true'
                },
                {
                    common: 'Bee Balm',
                    botanical: 'Monarda didyma',
                    zone: '4',
                    light: 'Shade',
                    price: '4.59',
                    availability: '05/03/2006',
                    indoor: 'true'
                },
                {
                    common: 'Bergamot',
                    botanical: 'Monarda didyma',
                    zone: '4',
                    light: 'Shade',
                    price: '7.16',
                    availability: '04/27/2006',
                    indoor: 'true'
                },
                {
                    common: 'Black-Eyed Susan',
                    botanical: 'Rudbeckia hirta',
                    zone: 'Annual',
                    light: 'Sunny',
                    price: '9.80',
                    availability: '06/18/2006',
                    indoor: 'false'
                },
                {
                    common: 'Buttercup',
                    botanical: 'Ranunculus',
                    zone: '4',
                    light: 'Shade',
                    price: '2.57',
                    availability: '06/10/2006',
                    indoor: 'true'
                },
                {
                    common: 'Crowfoot',
                    botanical: 'Ranunculus',
                    zone: '4',
                    light: 'Shade',
                    price: '9.34',
                    availability: '04/03/2006',
                    indoor: 'true'
                },
                {
                    common: 'Butterfly Weed',
                    botanical: 'Asclepias tuberosa',
                    zone: 'Annual',
                    light: 'Sunny',
                    price: '2.78',
                    availability: '06/30/2006',
                    indoor: 'false'
                },
                {
                    common: 'Cinquefoil',
                    botanical: 'Potentilla',
                    zone: 'Annual',
                    light: 'Shade',
                    price: '7.06',
                    availability: '05/25/2006',
                    indoor: 'true'
                },
                {
                    common: 'Primrose',
                    botanical: 'Oenothera',
                    zone: '3 - 5',
                    light: 'Sunny',
                    price: '6.56',
                    availability: '01/30/2006',
                    indoor: 'false'
                },
                {
                    common: 'Gentian',
                    botanical: 'Gentiana',
                    zone: '4',
                    light: 'Sun or Shade',
                    price: '7.81',
                    availability: '05/18/2006',
                    indoor: 'false'
                },
                {
                    common: 'Blue Gentian',
                    botanical: 'Gentiana',
                    zone: '4',
                    light: 'Sun or Shade',
                    price: '8.56',
                    availability: '05/02/2006',
                    indoor: 'false'
                },
                {
                    common: 'Jacob\'s Ladder',
                    botanical: 'Polemonium caeruleum',
                    zone: 'Annual',
                    light: 'Shade',
                    price: '9.26',
                    availability: '02/21/2006',
                    indoor: 'true'
                },
                {
                    common: 'Greek Valerian',
                    botanical: 'Polemonium caeruleum',
                    zone: 'Annual',
                    light: 'Shade',
                    price: '4.36',
                    availability: '07/14/2006',
                    indoor: 'true'
                },
                {
                    common: 'California Poppy',
                    botanical: 'Eschscholzia californica',
                    zone: 'Annual',
                    light: 'Sunny',
                    price: '7.89',
                    availability: '03/27/2006',
                    indoor: 'false'
                },
                {
                    common: 'Shooting Star',
                    botanical: 'Dodecatheon',
                    zone: 'Annual',
                    light: 'Mostly Shady',
                    price: '8.60',
                    availability: '05/13/2006',
                    indoor: 'true'
                },
                {
                    common: 'Snakeroot',
                    botanical: 'Cimicifuga',
                    zone: 'Annual',
                    light: 'Shade',
                    price: '5.63',
                    availability: '07/11/2006',
                    indoor: 'true'
                },
                {
                    common: 'Cardinal Flower',
                    botanical: 'Lobelia cardinalis',
                    zone: '2',
                    light: 'Shade',
                    price: '3.02',
                    availability: '02/22/2006',
                    indoor: 'true'
                }
            ],
            proxy: {
                type: 'memory'
            },
            sorters: {
                property: 'common'
            }
        }, cfg)]);
    }
});