/*
 * File: app/controller/MyController.js
 *
 * This file was generated by Sencha Architect version 2.2.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.1.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.1.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.controller.MyController', {
    extend: 'Ext.app.Controller',

    onButtonToggle: function(button, pressed, eOpts) {
        var panel = button.up('panel');
        if (pressed) {
            panel.setSize(100, 200);
        } else {
            panel.setSize(400, 250);
        }
    },

    init: function(application) {
        this.control({
            "button#sizeToggle": {
                toggle: this.onButtonToggle
            }
        });
    }

});
