/*
 * File: app/view/MyGridPanel.js
 *
 * This file was generated by Sencha Architect version 2.0.0.
 * http://www.sencha.com/products/architect/
 *
 * This file requires use of the Ext JS 4.0.x library, under independent license.
 * License of Sencha Architect does not include license for Ext JS 4.0.x. For more
 * details see http://www.sencha.com/license or contact license@sencha.com.
 *
 * This file will be auto-generated each and everytime you save your project.
 *
 * Do NOT hand edit this file.
 */

Ext.define('MyApp.view.MyGridPanel', {
    extend: 'Ext.grid.Panel',

    height: 350,
    width: 600,
    title: 'Array Grid',
    store: 'MyArrayStore',

    initComponent: function() {
        var me = this;

        Ext.applyIf(me, {
            viewConfig: {

            },
            columns: [
                {
                    xtype: 'gridcolumn',
                    dataIndex: 'company',
                    flex: 1,
                    text: 'Company'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'price',
                    text: 'Price'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'change',
                    text: 'Change'
                },
                {
                    xtype: 'numbercolumn',
                    width: 75,
                    dataIndex: 'pctChange',
                    text: 'PctChange'
                },
                {
                    xtype: 'datecolumn',
                    width: 85,
                    dataIndex: 'lastChange',
                    text: 'LastChange'
                },
                {
                    xtype: 'actioncolumn',
                    width: 50
                }
            ]
        });

        me.callParent(arguments);
    }

});